title: Meta Image Labs
description: 브라우저에서 100% 로컬로 실행되는 안전한 이미지, 파일 변환 솔루션. 영상을 고품질 gif로 변환 프로그램, 해킹 걱정 없는 디지털 부업 필수 툴.
keywords: "이미지 프로그램, 파일 변환, 안전한 파일 업로드, 개인정보 보호, 브라우저 파일 변환"
url: https://iiimaze.github.io
baseurl: ""

permalink: pretty
lang: ko-KR
timezone: Asia/Seoul

plugins:
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: "blog"
      type: "pages"
    values:
      pagination:
        enabled: true
        collection: posts
        per_page: 5
        permalink: "/blog/page:num/"
        sort_field: "date"
        sort_reverse: true
        trail:
          before: 2
          after: 2

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md

utterances:
  repo: iiimaze/iiimaze.github.io

naver_site_verification: "98a9d5133fc8d043f732b2bbd09d922e373f2966"
adsense_client: "ca-pub-1404060643961114"

org:
  sameAs:
    - "https://github.com/iiimaze"
